# Generated by Django 4.1.5 on 2023-02-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_main', '0002_historyinfo_remove_message_userid_message_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='userName',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
