# Generated by Django 4.1.5 on 2023-02-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_main', '0004_remove_message_user_alter_message_reciverid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('profilePic', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='groupinfo',
            name='u_id',
        ),
        migrations.DeleteModel(
            name='HistoryInfo',
        ),
        migrations.RemoveField(
            model_name='logininfo',
            name='u_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='reciverId',
        ),
        migrations.RemoveField(
            model_name='message',
            name='u_id',
        ),
        migrations.RemoveField(
            model_name='mobileinfo',
            name='u_id',
        ),
        migrations.DeleteModel(
            name='GroupInfo',
        ),
        migrations.DeleteModel(
            name='LoginInfo',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MobileInfo',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
