# Generated by Django 4.1.5 on 2023-02-27 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_main', '0006_person_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='id',
            new_name='P_id',
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('profilePic', models.ImageField(blank=True, null=True, upload_to='')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_main.person')),
            ],
        ),
    ]
