# Generated by Django 4.1.5 on 2023-02-27 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_main', '0007_rename_id_person_p_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reportId', models.AutoField(primary_key=True, serialize=False)),
                ('report', models.CharField(max_length=250)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_main.user')),
            ],
        ),
    ]
