# Generated by Django 4.1.5 on 2023-02-27 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_main', '0008_report'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='ReportInfo',
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusOfReport', models.BooleanField(default=False)),
                ('reportId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_main.reportinfo')),
            ],
        ),
    ]
