# Generated by Django 4.1.5 on 2023-02-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_main', '0010_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='mobile',
            field=models.CharField(default='', max_length=10),
        ),
    ]
