# Generated by Django 4.1.5 on 2023-02-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_main', '0013_alter_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='message',
            name='mes',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
