# Generated by Django 4.1.5 on 2023-02-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_main', '0014_message_file_message_image_message_mes_message_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='mes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
