# Generated by Django 4.1.5 on 2023-02-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_main', '0015_alter_message_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emailId',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
