# Generated by Django 4.1.5 on 2023-02-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_main', '0016_user_emailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='pic'),
        ),
    ]
