# Generated by Django 4.1.5 on 2023-02-28 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_main', '0017_alter_user_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='')),
            ],
        ),
    ]
