# Generated by Django 4.1.5 on 2023-02-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_main', '0018_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='images/'),
        ),
    ]
