# Generated by Django 4.1.5 on 2023-02-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_main', '0019_alter_img_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
