# Generated by Django 4.1.5 on 2023-02-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_main', '0021_alter_user_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profilePic',
        ),
        migrations.AddField(
            model_name='person',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='pic/'),
        ),
    ]
