# Generated by Django 4.1.5 on 2023-02-28 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_main', '0022_remove_user_profilepic_person_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useName', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=8)),
                ('P_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_main.person')),
            ],
        ),
    ]
