# Generated by Django 4.0.1 on 2023-03-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_main', '0024_alter_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='emailId',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
